# Version de l'OpenAPI
openapi: 3.0.0

# Informations générales sur l'API
info:
  title: Transaction API
  description: API for managing transactions and related operations.
  version: 1.0.0

# Serveur sur lequel l'API est hébergée
servers:
  - url: http://localhost:3000/api/v1
    description: Local development server

# Définition des différents chemins (routes) de l'API
paths:

  # Route unique pour mettre à jour une transaction (générale ou note)
  /transactions/{transactionId}:
    patch:
      security:
        - BearerAuth: []  # Correction ici : le nom doit correspondre à la définition ci-dessous
      tags:
        - Transaction Module
      summary: Update Transaction Information or Note
      description: API to update specific fields of a transaction, including notes.
      parameters:
        - name: transactionId
          in: path
          required: true
          schema:
            type: string
          description: ID of the transaction to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                field:
                  type: string
                  description: The field to update (e.g., status, category, note)
                value:
                  type: string
                  description: The new value for the field
              required:
                - field
                - value
      responses:
        '200':
          description: Transaction updated successfully
        '400':
          description: Invalid request payload
        '401':
          description: Unauthorized access
        '404':
          description: Transaction not found
        '500':
          description: Internal server error

# Composants réutilisables
components:
  securitySchemes:
    BearerAuth:  # Définition du schéma de sécurité Bearer
      type: http
      scheme: bearer
      bearerFormat: JWT  # Format du token (JSON Web Token)
  schemas:
    ApiResponse:
      type: object
      properties:
        status:
          type: string
        message:
          type: string
