swagger: '2.0'
info:
  title: Transaction API
  description: API for managing transactions and related operations.
  version: '1.0.0'

host: localhost:3000
basePath: /api/v1
schemes:
  - http

paths:
  /user/transactionId:
    patch:
      security:
        - Bearer: []  # Correspondance avec la définition de sécurité
      tags:
        - Transaction Module
      summary: Update Transaction Information or Note
      description: API to update specific fields of a transaction, including notes.
      parameters:
        - in: body
          name: body
          description: Fields to update in the transaction
          required: true
          schema:
            $ref: '#/definitions/TransactionUpdate'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction updated successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid request payload
        '401':
          description: Unauthorized access
        '404':
          description: Transaction not found
        '500':
          description: Internal server error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

definitions:
  TransactionUpdate:
    type: object
    properties:
      field:
        type: string
        description: The field to update (e.g., status, category, note)
      value:
        type: string
        description: The new value for the field
    required:
      - field
      - value

  ApiResponse:
    type: object
    properties:
      status:
        type: string
      message:
        type: string

        
