swagger: '2.0'
info:
  title:  Bank Argent Transaction API documentation
  description: API for managing transactions and related operations.
  version: '1.0.0'

host: localhost:3000
basePath: /api/v1
schemes:
  - http

paths:
  /user/transactionId:
    patch:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Update Transaction Information
      description: API to update transaction fields including note, category, and status.
      parameters:
        - in: body
          name: body
          description: Fields to update in the transaction. All fields must be provided.
          required: true
          schema:
            $ref: '#/definitions/TransactionUpdate'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction updated successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid request payload
        '401':
          description: Unauthorized access
        '404':
          description: Transaction not found
        '500':
          description: Internal server error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

definitions:
  TransactionUpdate:
    type: object
    properties:
      note:
        type: string
        description: The note associated with the transaction.
      category:
        type: string
        description: The category of the transaction.
      status:
        type: string
        description: The current status of the transaction.
    required:
      - note
      - category
      - status

  ApiResponse:
    type: object
    properties:
      status:
        type: string
      message:
        type: string
